config/routes.rb
MongoSpineRc5::Application.routes.draw do
  resources :bees
  
  resources :pages

  match 'app' => 'pages#app'

  root :to => 'pages#index'

  
  match '/application.js' => Stitch::Server.new(:paths => ["app/assets/javascripts/app", "app/assets/javascripts/lib"])
  
  
end

app/models/bee.rb
class Bee
  include MongoMapper::Document

  key :name, String
  key :email, String
  key :username, String
  key :password, String
  key :interests, Set
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bees_controller.rb
class BeesController < ApplicationController

  # GET /bees
  # GET /bees.json
  def index
    @bees = Bee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bees }
    end
  end

  # GET /bees/1
  # GET /bees/1.json
  def show
    @bee = Bee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bee }
    end
  end

  # GET /bees/new
  # GET /bees/new.json
  def new
    @bee = Bee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bee }
    end
  end

  # GET /bees/1/edit
  def edit
    @bee = Bee.find(params[:id])
  end

  # POST /bees
  # POST /bees.json
  def create
    @bee = Bee.new(params[:bee])

    respond_to do |format|
      if @bee.save
        format.html { redirect_to @bee, notice: 'Bee was successfully created.' }
        format.json { render json: @bee, status: :created, location: @bee }
      else
        format.html { render action: "new" }
        format.json { render json: @bee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bees/1
  # PUT /bees/1.json
  def update
    @bee = Bee.find(params[:id])

    respond_to do |format|
      if @bee.update_attributes(params[:bee])
        format.html { redirect_to @bee, notice: 'Bee was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bees/1
  # DELETE /bees/1.json
  def destroy
    @bee = Bee.find(params[:id])
    @bee.destroy

    respond_to do |format|
      format.html { redirect_to bees_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bees }
    end
  end

  def app
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bees_helper.rb
module BeesHelper
end

app/views/bees/_form.html.haml
.content_panel

  = form_for @bee do |f|
    -if @bee.errors.any?
      #error_explanation
        %h2= "#{pluralize(@bee.errors.count, "error")} prohibited this bee from being saved:"
        %ul
          - @bee.errors.full_messages.each do |msg|
            %li= msg

    = f.text_field :name  ,{"placeholder"=>"name"}
    = f.text_field :username ,{"placeholder"=>"username"}

    = f.text_field :email ,{"placeholder"=>"email"}
    = f.text_field :password ,{"placeholder"=>"password"}

app/views/bees/edit.html.haml
.title 
  %span change it, but it's still going to be a bee

= render 'form'

.action_bar
  .action_button
    %a{:href => "#",:onclick=>"$('form').submit()"} Save

  .action_button
    = link_to 'Back', bees_path

app/views/bees/index.html.haml
.title 
	%span This are all the bee's

%ul.list.content_panel
	%li.header
		%span Name
		%span Email
		%span Username
		%span Password

	- @bees.each do |bee|
		%li
			%span= bee.name
			%span= bee.email
			%span= bee.username
			%span= bee.password
			%span.button= link_to 'Edit', edit_bee_path(bee)
			%span.button= link_to 'Destroy', bee, :confirm => 'Are you sure?', :method => :delete

.action_bar

	.action_button
		= link_to 'New', new_bee_path

app/views/bees/new.html.haml
.title 
  %span Create a new Bee

= render 'form'

.action_bar
  .action_button
    %a{:href => "#",:onclick=>"$('form').submit()"} Save

  .action_button
    = link_to 'Back', bees_path

app/views/bees/show.html.haml
.title
  %span#notice= notice

%ul.list.content_panel
  %li
    %span 
      Name:
      = @bee.name
  %li
    %span 
      Email:
      = @bee.email
  %li
    %span
      Username:
      = @bee.username
  %li
    %span
      Password:
      = @bee.password

.action_bar
 
  .action_button
    = link_to 'Edit', edit_bee_path(@bee)

  .action_button
    = link_to 'Back', bees_path

app/views/layouts/application.html.haml
!!!Strict
%html{ }
	%head
		%title Invoice App
		%meta{'http-equiv'=>"Content-Type", :content=>"text/html; charset=utf-8"}/
		%meta{'http-equiv'=>"Content-Language", :content=>"en-us"}/
		
		= stylesheet_link_tag :application
		= javascript_include_tag :vendor
		%script{:src => "/application.js", :type => 'text/javascript', :charset => 'utf-8'}

	%body
		#header
			.wrapper
				%span.logo Bee Creator by Roberto Rodriguez
				.menu
					.button.standard.active
						= link_to 'Standard App', bees_path
					.button.dynamic
						%a{:href=>"/app"} Dynamic App
		#content
			.wrapper
				= yield

		#footer
			.wrapper
				.contact_info
					@rodriguezartav

app/views/pages/app.html.haml
.title 
	%span Javascript Front End
	
#bee
	.content

:javascript
	var exports = this;
	jQuery(function(){
		var App = require("app");
		exports.App = new App({el: $("body")});
	})

app/views/pages/index.html.haml
.title 
	%span Javascript Front End

.content_panel
	.grid_selector
		%h1 Welcome to the Rails 3.1 with Javascript Front-End Example
		%h2 Pick you application

		.option
			= link_to 'Standard App', bees_path

		.option
			%a{:href=>"/app"} Dynamic App